version: "3.9"
services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: lernex
      POSTGRES_PASSWORD: lernex
      POSTGRES_DB: lernex
    ports:
      - "5432:5432"
    volumes:
      - lernex_pg:/var/lib/postgresql/data

volumes:
  lernex_pg:
